# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-09 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_from', models.TimeField(blank=True, null=True)),
                ('monday_to', models.TimeField(blank=True, null=True)),
                ('tuesday_from', models.TimeField(blank=True, null=True)),
                ('tuesday_to', models.TimeField(blank=True, null=True)),
                ('wednesday_from', models.TimeField(blank=True, null=True)),
                ('wednesday_to', models.TimeField(blank=True, null=True)),
                ('thursday_from', models.TimeField(blank=True, null=True)),
                ('thursday_to', models.TimeField(blank=True, null=True)),
                ('friday_from', models.TimeField(blank=True, null=True)),
                ('friday_to', models.TimeField(blank=True, null=True)),
                ('saturday_from', models.TimeField(blank=True, null=True)),
                ('saturday_to', models.TimeField(blank=True, null=True)),
                ('sunday_from', models.TimeField(blank=True, null=True)),
                ('sunday_to', models.TimeField(blank=True, null=True)),
                ('availability_increment', models.IntegerField(choices=[(10, 10), (15, 15), (20, 20), (30, 30), (40, 40), (45, 45), (60, 60), (90, 90), (120, 120), (180, 180)], default=10)),
                ('booking_duration', models.IntegerField(choices=[(10, 10), (20, 20), (30, 30), (40, 40), (50, 50), (60, 60), (70, 70), (80, 80), (90, 90), (100, 100), (110, 110), (120, 120)], default=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='socialaccount.SocialAccount')),
                ('social_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='availability_prefs', to='socialaccount.SocialAccount')),
            ],
        ),
    ]
