# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-09 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingavailability',
            old_name='social_account',
            new_name='account_social',
        ),
    ]
