# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-10 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_bookingavailability_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingavailability',
            name='booking_duration',
            field=models.IntegerField(),
        ),
    ]
