# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-12 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_auto_20180210_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingavailability',
            name='account_social',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availability_prefs', to='socialaccount.SocialAccount'),
        ),
    ]
