# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-16 22:59
from __future__ import unicode_literals

import bookings.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('bookings', '0006_auto_20180212_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField(blank=True)),
                ('end_time', models.DateTimeField(blank=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=200, validators=[django.core.validators.EmailValidator(), bookings.models.custom_validate_kcl_email])),
                ('duration', models.IntegerField()),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('outlook_id', models.CharField(max_length=1000)),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='socialaccount.SocialAccount')),
            ],
        ),
    ]
