# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-16 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='outlook_id',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
