# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-17 20:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_auto_20180216_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='email',
            field=models.EmailField(max_length=200, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
