# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-17 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_auto_20180217_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='outlook_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
