# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-12 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_auto_20180217_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingavailability',
            name='lunch_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingavailability',
            name='lunch_to',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
