# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-13 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_auto_20180412_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingavailability',
            name='availability_increment',
            field=models.IntegerField(choices=[(5, 5), (10, 10), (15, 15), (20, 20), (30, 30), (40, 40), (45, 45), (60, 60)], default=10),
        ),
    ]
